### ISSUE TITLE
Update lens model parameters for z_lens = 1.0

### ISSUE THREAD

**Issue by cdfassnacht** [jwhsueh/SHARP_jw#10]

**Comment by jwhsueh** [comment]
zl=1.0, zs=1.5
2-SIE model point source has a position shift. Need to double check.
Table 2 has SIE+expdisk updated but not 2-SIE part

**Comment by jwhsueh** [comment]
Source position is not in Table 2. And the source position of 2-SIE model doesn't change at all. I was wrong yesterday.
Table 2 is all updated. Issue close.
