### ISSUE TITLE
Convert from emulateapj to MNRAS style

### ISSUE THREAD

**Issue by cdfassnacht** [jwhsueh/SHARP_jw#4]
Nick Rumbaugh has recently done this, so he can give pointers.

**Comment by jwhsueh** [comment]
Change to MNRAS template and uploaded
Has two compile problems:
1) The figures doesn't show
2) The \bibliographystyle commend gives error

**Comment by jwhsueh** [comment]
Now the figures are displayed successfully. Still need to fix \bibstyle.

**Comment by jwhsueh** [comment]
bibtex problem fix. case closed
