### ISSUE TITLE
Update Table 4

### ISSUE THREAD

**Issue by cdfassnacht** [jwhsueh/SHARP_jw#5]
I think that it would be good if Table 4, which shows the radio and model-predicted flux ratios, would have three model columns.  The first would be SIE-only model (similar or the same as in Marlow et al.), the second and third would be the predictions of the SIE+expdisk and the 2SIE models.

**Comment by jwhsueh** [comment]
table updated. The 2-SIE model has better prediction on flux ratio then SIE+expdisk. I would like to add a part in Discussion about this.
But for the table, case closed.
